name: Release

on:
  push:
    tags:
      - 'v*'  # This will trigger the action on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Use the latest version of checkout action

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Specify the .NET version to be used

    - name: Restore dependencies
      run: dotnet restore  # Restore project dependencies

    - name: Build the project
      run: dotnet build --configuration Release  # Build the project in Release configuration

    # Publish the project as a single file
    - name: Publish the project as a single file
      run: |
        dotnet publish -c Release -r win-x64 --self-contained false /p:PublishSingleFile=true /p:PublishTrimmed=true --output ./publish
      # Use win-x64 for Windows target. You can replace with linux-x64 or osx-x64 for other platforms.
      # self-contained=false: The application will not package the .NET runtime (change to true if needed).
      # PublishSingleFile=true: Ensures the output is a single executable file.
      # PublishTrimmed=true: This trims unused assemblies to reduce size.

    # Zip the entire published folder
    - name: Zip the publish folder (Full)
      run: |
        powershell Compress-Archive -Path ./publish/* -DestinationPath ./WintonFull.zip
      # Compress the entire publish folder into WintonFull.zip
    
    # Zip only the single-file executable
    - name: Zip the single executable
      run: |
        $singleFile = Get-ChildItem -Path ./publish/ | Where-Object { $_.Name -like "*.exe" }
        powershell Compress-Archive -Path $singleFile.FullName -DestinationPath ./WintonSingleFile.zip
      # Compress the single-file executable into WintonSingleFile.zip

    # Create a GitHub Release
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token from repository secrets
      with:
        tag_name: ${{ github.ref_name }}  # Use the tag name (e.g., v1.0.0)
        release_name: Release ${{ github.ref_name }}  # Name the release based on the tag
        draft: false
        prerelease: false

    # Upload full publish folder as zip file
    - name: Upload full publish folder
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token from repository secrets
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}  # Upload to the release created earlier
        asset_path: ./WintonFull.zip  # Path to the full publish zip
        asset_name: WintonFull.zip  # Name of the full publish zip file
        asset_content_type: application/zip  # Specify the asset content type as a zip file

    # Upload single-file executable as zip file
    - name: Upload single-file executable
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token from repository secrets
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}  # Upload to the release created earlier
        asset_path: ./WintonSingleFile.zip  # Path to the single executable zip
        asset_name: WintonSingleFile.zip  # Name of the single executable zip file
        asset_content_type: application/zip  # Specify the asset content type as a zip file
